import type { ScholarshipType } from './constants.ts';

/**
 * Raw scholarship records in the scraper's canonical shape. This snapshot is
 * used (a) to seed a fresh database and (b) as the offline fallback for the
 * nightly crawl when SCRAPER_LIVE=false. Every record keeps its
 * `officialSourceUrl` and a `lastScrapedAt` timestamp for source auditing.
 *
 * These entries reflect real national/state scholarship programmes. Verify the
 * live portal before relying on amounts or deadlines; the crawler refreshes
 * them daily at 00:00 IST.
 */
export interface RawScholarship {
  provider: string;
  title: string;
  type: ScholarshipType;
  amount: number;
  amountDescription: string;
  degree: string[];
  currentYearAllowed: string[];
  incomeLimit?: number;
  marksMin?: number;
  /** True when the scheme is reserved for students with a documented disability. */
  disabilityRequired?: boolean;
  category: string[];
  stateDomicile: string[];
  gender: string[];
  deadline?: string; // ISO
  requiredDocuments: string[];
  selectionProcess: string[];
  aptitudeTestRequired: boolean;
  renewalCriteria?: { minimumCgpa?: number; minimumAttendance?: number; notes?: string };
  officialSourceUrl: string;
  applicationMode: 'native' | 'external';
  externalPortalUrl?: string;
  applicationSteps: string[];
  description: string;
  examPattern?: {
    name?: string;
    durationMinutes: number;
    totalQuestions?: number;
    negativeMarking?: number;
    sections: { name: string; questions: number; durationMinutes: number; topics: string[] }[];
  };
  tags: string[];
}

function deadlineInDays(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

export const SCHOLARSHIP_SNAPSHOT: RawScholarship[] = [
  {
    provider: 'National Scholarship Portal (NSP)',
    title: 'Post Matric Scholarship for SC Students',
    type: 'Government',
    amount: 120000,
    amountDescription:
      'Full tuition reimbursement plus monthly maintenance allowance (₹700–₹1,200 by course group).',
    degree: ['Undergraduate', 'Postgraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['Any'],
    incomeLimit: 250000,
    marksMin: 0,
    category: ['SC'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(45),
    requiredDocuments: [
      'Income Certificate',
      'Category Certificate',
      'Class 10 Marksheet',
      'Class 12 Marksheet',
      'Domicile Proof',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Online application on NSP', 'Institute verification', 'State nodal officer approval', 'DBT disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75, notes: 'Annual renewal on NSP with fresh income certificate.' },
    officialSourceUrl: 'https://scholarships.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://scholarships.gov.in/',
    applicationSteps: [
      'Register on NSP as a fresh applicant',
      'Fill academic and bank details',
      'Upload income and category certificates',
      'Submit and note the application ID',
      'Track institute and state verification',
    ],
    description:
      'Central assistance for SC students pursuing post-matriculation courses to reduce dropout and support completion.',
    tags: ['post-matric', 'SC', 'central', 'DBT'],
  },
  {
    provider: 'National Scholarship Portal (NSP)',
    title: 'Central Sector Scheme of Scholarship (Merit)',
    type: 'Merit-Based',
    amount: 20000,
    amountDescription: '₹10,000 per year for graduation, ₹20,000 per year for post-graduation.',
    degree: ['Undergraduate', 'Postgraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['1st Year', '2nd Year', '3rd Year'],
    incomeLimit: 800000,
    marksMin: 80,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(30),
    requiredDocuments: [
      'Class 12 Marksheet',
      'Income Certificate',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
      'Signature',
    ],
    selectionProcess: ['Merit list from Class 12 board results', 'Online application on NSP', 'Verification', 'Annual disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumCgpa: 6, minimumAttendance: 75, notes: '60% marks in each year for renewal.' },
    officialSourceUrl: 'https://scholarships.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://scholarships.gov.in/',
    applicationSteps: [
      'Check Class 12 merit cut-off for your board',
      'Register and complete NSP application',
      'Upload board marksheet and bonafide',
      'Await state and central verification',
    ],
    description:
      'For students in the top 20th percentile of their Class 12 board pursuing regular degree courses.',
    tags: ['merit', 'central', 'NSP'],
  },
  {
    provider: 'AICTE',
    title: 'AICTE Pragati Scholarship for Girls (Technical)',
    type: 'Government',
    amount: 50000,
    amountDescription: '₹50,000 per year towards tuition and incidentals for AICTE-approved technical programmes.',
    degree: ['Undergraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['1st Year'],
    incomeLimit: 800000,
    marksMin: 0,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: ['Female'],
    deadline: deadlineInDays(60),
    requiredDocuments: [
      'Income Certificate',
      'Class 12 Marksheet',
      'Category Certificate',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Online AICTE application', 'Institute scrutiny', 'Merit-based selection', 'DBT disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75, notes: 'Continue in the same approved institute and programme.' },
    officialSourceUrl: 'https://www.aicte-india.org/schemes/students-development-schemes',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.aicte-india.org/',
    applicationSteps: [
      'Confirm admission to an AICTE-approved institute',
      'Create an AICTE Pragati login',
      'Upload income and admission proof',
      'Submit before the portal deadline',
    ],
    description:
      'Encourages girl students to pursue technical education by covering a substantial part of annual costs.',
    tags: ['girls', 'AICTE', 'technical'],
  },
  {
    provider: 'AICTE',
    title: 'AICTE Saksham Scholarship for Differently Abled Students',
    type: 'Government',
    amount: 50000,
    amountDescription: '₹50,000 per year for tuition and incidentals.',
    degree: ['Undergraduate'],
    currentYearAllowed: ['1st Year'],
    incomeLimit: 800000,
    marksMin: 0,
    disabilityRequired: true,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(60),
    requiredDocuments: [
      'Disability Certificate',
      'Income Certificate',
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Online AICTE application', 'Institute verification', 'Selection committee review', 'DBT disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75 },
    officialSourceUrl: 'https://www.aicte-india.org/schemes/students-development-schemes',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.aicte-india.org/',
    applicationSteps: [
      'Hold a valid disability certificate (40% or more)',
      'Apply through the AICTE Saksham portal',
      'Upload disability and income documents',
      'Track approval status',
    ],
    description:
      'Financial support for differently abled students admitted to AICTE-approved degree/diploma programmes.',
    tags: ['disability', 'AICTE', 'technical'],
  },
  {
    provider: 'Government of Maharashtra',
    title: 'Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti',
    type: 'State Government',
    amount: 60000,
    amountDescription: 'Tuition fee waiver for eligible Maharashtra domicile students.',
    degree: ['Undergraduate', 'Postgraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['1st Year', '2nd Year', '3rd Year', '4th Year'],
    incomeLimit: 800000,
    marksMin: 0,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['Maharashtra'],
    gender: [],
    deadline: deadlineInDays(50),
    requiredDocuments: [
      'Domicile Proof',
      'Income Certificate',
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['MahaDBT portal application', 'Institute verification', 'State approval', 'Direct fee credit'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75, notes: 'Renew annually on MahaDBT.' },
    officialSourceUrl: 'https://mahadbt.maharashtra.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://mahadbt.maharashtra.gov.in/',
    applicationSteps: [
      'Create a MahaDBT profile with Aadhaar-linked login (no ID stored on our side)',
      'Select the fee waiver scheme',
      'Upload domicile and income proof',
      'Submit and track at the institute level',
    ],
    description:
      'Maharashtra state tuition-fee reimbursement for students from families with annual income under ₹8 lakh.',
    tags: ['Maharashtra', 'fee-waiver', 'state'],
  },
  {
    provider: 'Government of Maharashtra',
    title: 'Post Matric Scholarship (Maharashtra)',
    type: 'State Government',
    amount: 40000,
    amountDescription: 'Maintenance allowance and compulsory non-fee grant.',
    degree: ['Undergraduate', 'Postgraduate'],
    currentYearAllowed: ['Any'],
    incomeLimit: 250000,
    marksMin: 0,
    category: ['SC', 'ST', 'OBC', 'Minority'],
    stateDomicile: ['Maharashtra'],
    gender: [],
    deadline: deadlineInDays(40),
    requiredDocuments: [
      'Domicile Proof',
      'Income Certificate',
      'Category Certificate',
      'Class 10 Marksheet',
      'Bank Passbook',
    ],
    selectionProcess: ['MahaDBT application', 'Institute verification', 'Social welfare department sanction'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75 },
    officialSourceUrl: 'https://mahadbt.maharashtra.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://mahadbt.maharashtra.gov.in/',
    applicationSteps: [
      'Log in to MahaDBT',
      'Choose Post Matric Scholarship',
      'Upload category and income proof',
      'Submit and monitor sanction',
    ],
    description:
      'State maintenance support for reserved-category and minority students in Maharashtra post-matriculation.',
    tags: ['Maharashtra', 'post-matric', 'state'],
  },
  {
    provider: 'Tata Consultancy Services',
    title: 'TCS Ignite Scholarship',
    type: 'Corporate CSR',
    amount: 100000,
    amountDescription: 'Up to ₹1,00,000 per year towards tuition for engineering students.',
    degree: ['Undergraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['1st Year', '2nd Year', '3rd Year', '4th Year'],
    incomeLimit: 800000,
    marksMin: 60,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(35),
    requiredDocuments: [
      'Income Certificate',
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Online application', 'Aptitude test', 'Technical interview', 'Award'],
    aptitudeTestRequired: true,
    renewalCriteria: { minimumCgpa: 6.5, notes: 'Maintain good academic standing; annual review.' },
    officialSourceUrl: 'https://www.tcs.com/corporate-social-responsibility',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.tcs.com/corporate-social-responsibility',
    applicationSteps: [
      'Register on the TCS scholarship portal',
      'Complete the online aptitude assessment',
      'Clear the interview round',
      'Receive award and maintain renewal CGPA',
    ],
    description:
      'Corporate CSR scholarship for meritorious engineering students with demonstrated financial need.',
    tags: ['CSR', 'engineering', 'aptitude-test'],
    examPattern: {
      name: 'TCS Ignite Online Aptitude Test',
      durationMinutes: 60,
      totalQuestions: 12,
      negativeMarking: 0,
      sections: [
        { name: 'Quantitative', questions: 4, durationMinutes: 20, topics: ['Percentages', 'Ratios', 'Averages'] },
        { name: 'Verbal', questions: 3, durationMinutes: 15, topics: ['Synonyms', 'Reading'] },
        { name: 'Logical', questions: 3, durationMinutes: 15, topics: ['Number Series', 'Odd One Out'] },
        { name: 'General Knowledge', questions: 2, durationMinutes: 10, topics: ['Government Schemes'] },
      ],
    },
  },
  {
    provider: 'Reliance Foundation',
    title: 'Reliance Foundation Undergraduate Scholarship',
    type: 'Foundation',
    amount: 200000,
    amountDescription: 'Up to ₹2,00,000 total grant across the undergraduate programme.',
    degree: ['Undergraduate'],
    currentYearAllowed: ['1st Year'],
    incomeLimit: 1500000,
    marksMin: 60,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(55),
    requiredDocuments: [
      'Class 12 Marksheet',
      'Income Certificate',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Online application', 'Aptitude test', 'Personal interview', 'Award'],
    aptitudeTestRequired: true,
    renewalCriteria: { minimumCgpa: 6, notes: 'Annual academic review.' },
    officialSourceUrl: 'https://www.scholarships.reliancefoundation.org/',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.scholarships.reliancefoundation.org/',
    applicationSteps: [
      'Apply on the Reliance Foundation portal',
      'Attempt the online aptitude test',
      'Attend the interview if shortlisted',
      'Confirm award acceptance',
    ],
    description:
      'Foundation grant supporting meritorious first-year undergraduates across disciplines in India.',
    tags: ['foundation', 'undergraduate', 'aptitude-test'],
    examPattern: {
      name: 'Reliance Foundation Aptitude Assessment',
      durationMinutes: 45,
      totalQuestions: 12,
      negativeMarking: 0,
      sections: [
        { name: 'Quantitative', questions: 4, durationMinutes: 15, topics: ['Percentages', 'Averages'] },
        { name: 'Verbal', questions: 3, durationMinutes: 10, topics: ['Synonyms'] },
        { name: 'Logical', questions: 3, durationMinutes: 12, topics: ['Number Series'] },
        { name: 'General Knowledge', questions: 2, durationMinutes: 8, topics: ['Education Basics'] },
      ],
    },
  },
  {
    provider: 'University Grants Commission (UGC)',
    title: 'UGC Indira Gandhi PG Scholarship for Single Girl Child',
    type: 'Government',
    amount: 36200,
    amountDescription: '₹36,200 per year for two years of post-graduation.',
    degree: ['Postgraduate'],
    currentYearAllowed: ['1st Year'],
    incomeLimit: 800000,
    marksMin: 60,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: ['Female'],
    deadline: deadlineInDays(25),
    requiredDocuments: [
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
      'Signature',
    ],
    selectionProcess: ['UGC online application', 'University verification', 'UGC selection', 'Disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumCgpa: 6, notes: 'Maintain 60% in the first year for renewal.' },
    officialSourceUrl: 'https://www.ugc.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.ugc.gov.in/',
    applicationSteps: [
      'Register on the UGC scholarship portal',
      'Upload PG admission and marksheet proof',
      'Submit through your university',
      'Track UGC approval',
    ],
    description:
      'For a single girl child pursuing a regular postgraduate degree in a recognised university.',
    tags: ['UGC', 'girls', 'postgraduate'],
  },
  {
    provider: 'Government of Karnataka',
    title: 'Karnataka Vidyasiri Post Matric Scholarship',
    type: 'State Government',
    amount: 45000,
    amountDescription: 'Fee reimbursement plus maintenance for eligible Karnataka students.',
    degree: ['Undergraduate', 'Postgraduate'],
    currentYearAllowed: ['Any'],
    incomeLimit: 250000,
    marksMin: 0,
    category: ['SC', 'ST', 'OBC', 'Minority'],
    stateDomicile: ['Karnataka'],
    gender: [],
    deadline: deadlineInDays(48),
    requiredDocuments: [
      'Domicile Proof',
      'Income Certificate',
      'Category Certificate',
      'Class 10 Marksheet',
      'Bank Passbook',
    ],
    selectionProcess: ['Karnataka SSP portal application', 'Institute verification', 'Department approval', 'DBT'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75 },
    officialSourceUrl: 'https://ssp.postmatric.karnataka.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://ssp.postmatric.karnataka.gov.in/',
    applicationSteps: [
      'Register on the Karnataka State Scholarship Portal',
      'Select Vidyasiri post-matric scheme',
      'Upload domicile and income proof',
      'Submit and track verification',
    ],
    description:
      'Karnataka state scholarship for reserved-category students in post-matric courses.',
    tags: ['Karnataka', 'post-matric', 'state'],
  },
  {
    provider: 'National Scholarship Portal (NSP)',
    title: 'Top Class Education Scheme for SC Students',
    type: 'Government',
    amount: 200000,
    amountDescription:
      'Full tuition fee and non-refundable charges (up to ₹2,00,000 per year at private institutions) plus maintenance allowance for full-time courses in notified institutions.',
    degree: ['Undergraduate', 'Postgraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['Any'],
    incomeLimit: 800000,
    marksMin: 0,
    category: ['SC'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(45),
    requiredDocuments: [
      'Income Certificate',
      'Category Certificate',
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Apply on NSP', 'Institute selection within the allocated slot limit', 'Verification', 'Direct disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75, notes: 'Annual renewal on NSP with a fresh income certificate.' },
    officialSourceUrl: 'https://scholarships.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://scholarships.gov.in/',
    applicationSteps: [
      'Confirm admission to a full-time course at a notified institution',
      'Apply on NSP under Top Class Education Scheme',
      'Upload income and category certificates',
      'Track institute selection and disbursal',
    ],
    description:
      'Flagship central scheme covering full tuition and maintenance for meritorious SC students in full-time courses at notified institutions of excellence.',
    tags: ['SC', 'top-class', 'central', 'NSP'],
  },
  {
    provider: 'National Scholarship Portal (NSP)',
    title: 'Post Matric Scholarship for ST Students',
    type: 'Government',
    amount: 120000,
    amountDescription:
      'Full tuition fee reimbursement plus monthly maintenance allowance (₹225–₹1,200 by course group) for ST students in post-matriculation courses.',
    degree: ['Undergraduate', 'Postgraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['Any'],
    incomeLimit: 250000,
    marksMin: 0,
    category: ['ST'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(45),
    requiredDocuments: [
      'Income Certificate',
      'Category Certificate',
      'Class 10 Marksheet',
      'Class 12 Marksheet',
      'Domicile Proof',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Online application on NSP', 'Institute verification', 'State nodal officer approval', 'DBT disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75, notes: 'Annual renewal on NSP with fresh income certificate.' },
    officialSourceUrl: 'https://scholarships.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://scholarships.gov.in/',
    applicationSteps: [
      'Register on NSP as a fresh applicant',
      'Select the ST post-matric scheme',
      'Upload income and tribal community certificates',
      'Submit and track state verification',
    ],
    description:
      'Centrally sponsored post-matric assistance (Class XI to postgraduate) for Scheduled Tribe students studying in India.',
    tags: ['post-matric', 'ST', 'central', 'DBT'],
  },
  {
    provider: 'National Scholarship Portal (NSP)',
    title: 'Post Matric Scholarship for Minority Students',
    type: 'Minority',
    amount: 20000,
    amountDescription:
      'Admission and course/tuition fee reimbursement plus maintenance allowance as per NSP rates for minority students from families earning up to ₹2 lakh a year.',
    degree: ['Undergraduate', 'Postgraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['Any'],
    incomeLimit: 200000,
    marksMin: 50,
    category: ['Minority'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(40),
    requiredDocuments: [
      'Income Certificate',
      'Category Certificate',
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Online application on NSP', 'Institute verification', 'State sanction', 'Disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75, notes: 'Renew with fresh marks and income proof each year.' },
    officialSourceUrl: 'https://scholarships.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://scholarships.gov.in/',
    applicationSteps: [
      'Register on NSP',
      'Select the central post-matric minority scholarship',
      'Upload minority community and income certificates',
      'Submit and track sanction',
    ],
    description:
      'For meritorious minority community students from economically weaker sections in post-matriculation courses; 30% of awards are earmarked for girls.',
    tags: ['minority', 'post-matric', 'central'],
  },
  {
    provider: 'Department of Empowerment of Persons with Disabilities (DEPwD)',
    title: 'Post Matric Scholarship for Students with Disabilities',
    type: 'Government',
    amount: 150000,
    amountDescription:
      'Tuition allowance of up to ₹1,50,000 per year plus maintenance and book allowance (₹1,500 per year) for PwD students.',
    degree: ['Undergraduate', 'Postgraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['Any'],
    incomeLimit: 250000,
    marksMin: 0,
    disabilityRequired: true,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(40),
    requiredDocuments: [
      'Disability Certificate',
      'Income Certificate',
      'Class 10 Marksheet',
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Apply on NSP under the DEPwD scheme', 'Institute verification', 'DEPwD approval', 'Disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75 },
    officialSourceUrl: 'https://depwd.gov.in/en/scholarship-post-matric/',
    applicationMode: 'external',
    externalPortalUrl: 'https://scholarships.gov.in/',
    applicationSteps: [
      'Hold a valid disability certificate (40% or more)',
      'Apply on NSP under the DEPwD post-matric scheme',
      'Upload disability, income and academic proof',
      'Track institute and DEPwD verification',
    ],
    description:
      'Central post-matric assistance for students with disabilities, covering tuition allowance, maintenance allowance and book grant.',
    tags: ['disability', 'PwD', 'post-matric', 'central'],
  },
  {
    provider: 'AICTE',
    title: 'AICTE PG Scholarship for GATE/GPAT Qualified Students',
    type: 'Government',
    amount: 148800,
    amountDescription:
      '₹12,400 per month for the course duration (typically 2 years) for full-time GATE/GPAT-qualified postgraduate students.',
    degree: ['Postgraduate'],
    currentYearAllowed: ['1st Year', '2nd Year'],
    marksMin: 0,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(60),
    requiredDocuments: [
      'Entrance Exam Scorecard',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
      'Signature',
    ],
    selectionProcess: ['Register on the AICTE PG scholarship portal', 'Institute confirms admission with a valid GATE/GPAT score', 'Monthly disbursal'],
    aptitudeTestRequired: true,
    renewalCriteria: { notes: 'Satisfactory academic performance, certified by the institute head each term.' },
    officialSourceUrl: 'https://www.aicte-india.org/schemes/students-development-schemes',
    applicationMode: 'external',
    externalPortalUrl: 'https://aicte.nta.ac.in/',
    applicationSteps: [
      'Qualify GATE/GPAT and take admission to a full-time AICTE-approved PG programme',
      'Register on the AICTE portal with your score and bank details',
      'Institute verifies eligibility',
      'Receive the monthly stipend',
    ],
    description:
      'National stipend for full-time postgraduate students in AICTE-approved programmes who qualify GATE/GPAT.',
    tags: ['AICTE', 'postgraduate', 'GATE', 'GPAT', 'stipend'],
  },
  {
    provider: 'AICTE',
    title: 'AICTE Swanath Scholarship for Divyangjan',
    type: 'Government',
    amount: 50000,
    amountDescription:
      '₹50,000 per year for every year of study for specially abled students in AICTE-approved degree programmes.',
    degree: ['Undergraduate', 'Postgraduate'],
    currentYearAllowed: ['1st Year'],
    incomeLimit: 800000,
    marksMin: 0,
    disabilityRequired: true,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(70),
    requiredDocuments: [
      'Disability Certificate',
      'Income Certificate',
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Apply on the AICTE fellowship/Swanath portal', 'Institute scrutiny', 'AICTE selection', 'DBT disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75 },
    officialSourceUrl: 'https://www.aicte-india.org/schemes/students-development-schemes',
    applicationMode: 'external',
    externalPortalUrl: 'https://fellowship.aicte.gov.in/',
    applicationSteps: [
      'Hold a valid disability certificate (40% or more)',
      'Confirm admission to an AICTE-approved degree programme',
      'Apply on the AICTE Swanath portal',
      'Track approval and disbursal',
    ],
    description:
      'For specially abled (Divyangjan) students admitted to AICTE-approved technical/degree programmes.',
    tags: ['disability', 'AICTE', 'technical', 'PwD'],
  },
  {
    provider: 'AICTE',
    title: 'Prime Minister’s Special Scholarship Scheme (PMSSS) for J&K & Ladakh',
    type: 'Government',
    amount: 125000,
    amountDescription:
      'Full tuition fee up to ₹1.25 lakh per year (engineering/professional stream) plus a maintenance allowance of ₹1.00 lakh per year.',
    degree: ['Undergraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['1st Year'],
    incomeLimit: 800000,
    marksMin: 0,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['Jammu and Kashmir', 'Ladakh'],
    gender: [],
    deadline: deadlineInDays(15),
    requiredDocuments: [
      'Domicile Proof',
      'Income Certificate',
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Apply on the AICTE PMSSS portal', 'DTE J&K/Ladakh verifies domicile', 'Allotment to institutions outside J&K', 'Fee and maintenance disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75, notes: 'Continue in the same course/stream; renewal processed annually.' },
    officialSourceUrl: 'https://www.aicte-india.org/',
    applicationMode: 'external',
    externalPortalUrl: 'https://aicte-jk-scholarship-gov.in/',
    applicationSteps: [
      'Pass 10+2 from J&K/Ladakh with domicile of the UT',
      'Apply on the AICTE PMSSS portal within the window',
      'Get verified by the DTE of your UT',
      'Receive an allotment and fee/maintenance disbursal',
    ],
    description:
      'Special Scholarship Scheme under PM-USPY for domiciles of Jammu & Kashmir and Ladakh pursuing undergraduate studies outside the UTs.',
    tags: ['J&K', 'Ladakh', 'PMSSS', 'tuition'],
  },
  {
    provider: 'Ministry of Social Justice and Empowerment',
    title: 'National Overseas Scholarship for SC Students',
    type: 'Government',
    amount: 1540000,
    amountDescription:
      'Maintenance allowance of USD 15,400 per year plus actual tuition fees, airfare and contingency for Master’s/PhD studies abroad.',
    degree: ['Postgraduate', 'Doctorate'],
    currentYearAllowed: ['1st Year'],
    incomeLimit: 800000,
    marksMin: 60,
    category: ['SC'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(90),
    requiredDocuments: [
      'Income Certificate',
      'Category Certificate',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
      'Signature',
    ],
    selectionProcess: ['Apply on the NOS portal', 'Merit-cum-means shortlist', 'Document verification', 'Disbursal through the Indian Mission'],
    aptitudeTestRequired: false,
    renewalCriteria: { notes: 'Annual continuation subject to satisfactory academic progress.' },
    officialSourceUrl: 'https://nosmsje.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://nosmsje.gov.in/',
    applicationSteps: [
      'Obtain admission to a Master’s or PhD programme abroad',
      'Apply within the annual NOS window',
      'Upload income, category and admission proof',
      'Track selection and award',
    ],
    description:
      'Funds meritorious low-income SC students (also covers DNT and other notified groups) for Master’s/PhD studies at recognised universities abroad.',
    tags: ['overseas', 'SC', 'postgraduate', 'doctorate'],
  },
  {
    provider: 'University Grants Commission (UGC)',
    title: 'Rajiv Gandhi National Fellowship for SC/ST Students',
    type: 'Government',
    amount: 300000,
    amountDescription:
      '₹25,000 per month (JRF) rising to ₹28,000 (SRF), plus HRA and contingency grant, for up to 5 years of full-time M.Phil/PhD.',
    degree: ['Doctorate'],
    currentYearAllowed: ['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year'],
    marksMin: 0,
    category: ['SC', 'ST'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(120),
    requiredDocuments: ['Category Certificate', 'Bonafide / Enrolment Certificate', 'Bank Passbook', 'Photograph'],
    selectionProcess: ['Apply through the university on the UGC portal', 'Merit-based selection of postgraduate-qualified candidates', 'Fellowship disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { notes: 'Renewal each year based on research progress reports.' },
    officialSourceUrl: 'https://www.ugc.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.ugc.gov.in/',
    applicationSteps: [
      'Pass the PG examination and register for a full-time M.Phil/PhD',
      'Apply on the UGC fellowship portal',
      'Institute verifies your category and admission',
      'Track fellowship sanction and renewals',
    ],
    description:
      'National fellowship supporting SC/ST students pursuing full-time M.Phil and PhD research.',
    tags: ['fellowship', 'PhD', 'SC', 'ST', 'UGC'],
  },
  {
    provider: 'University Grants Commission (UGC)',
    title: 'Rajiv Gandhi National Fellowship for OBC/EWS Students',
    type: 'Government',
    amount: 300000,
    amountDescription:
      '₹25,000 per month (JRF) rising to ₹28,000 (SRF), plus HRA and contingency grant, for up to 5 years of full-time M.Phil/PhD.',
    degree: ['Doctorate'],
    currentYearAllowed: ['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year'],
    incomeLimit: 600000,
    marksMin: 0,
    category: ['OBC', 'EWS'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(120),
    requiredDocuments: ['Income Certificate', 'Category Certificate', 'Bonafide / Enrolment Certificate', 'Bank Passbook', 'Photograph'],
    selectionProcess: ['Apply through the university on the UGC portal', 'Merit-based selection of postgraduate-qualified candidates', 'Fellowship disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { notes: 'Renewal each year based on research progress reports.' },
    officialSourceUrl: 'https://www.ugc.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.ugc.gov.in/',
    applicationSteps: [
      'Pass the PG examination and register for a full-time M.Phil/PhD',
      'Apply on the UGC fellowship portal',
      'Institute verifies category and income certificate',
      'Track fellowship sanction and renewals',
    ],
    description:
      'National fellowship supporting OBC and EWS students pursuing full-time M.Phil and PhD research (family income under ₹6 lakh).',
    tags: ['fellowship', 'PhD', 'OBC', 'EWS', 'UGC'],
  },
  {
    provider: 'University Grants Commission (UGC)',
    title: 'Ishan Uday Special Scholarship Scheme (North East)',
    type: 'Government',
    amount: 54000,
    amountDescription:
      '₹5,400 per month (general degree) or ₹7,800 per month (technical/professional degree) for 10 months a year, for the first three years of study, plus a one-time book grant.',
    degree: ['Undergraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['1st Year', '2nd Year', '3rd Year'],
    incomeLimit: 450000,
    marksMin: 0,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['Arunachal Pradesh', 'Assam', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Sikkim', 'Tripura'],
    gender: [],
    deadline: deadlineInDays(60),
    requiredDocuments: [
      'Domicile Proof',
      'Income Certificate',
      'Class 12 Marksheet',
      'Bonafide / Enrolment Certificate',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Apply on the UGC portal after Class 12', 'Institute forwards the application', 'UGC merit-based selection', 'Disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75, notes: 'Renewal for up to three years of study.' },
    officialSourceUrl: 'https://www.ugc.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.ugc.gov.in/',
    applicationSteps: [
      'Pass Class 12 with domicile of a North-Eastern state',
      'Apply online under Ishan Uday',
      'Upload domicile and income proof',
      'Track selection and monthly disbursal',
    ],
    description:
      'UGC scholarship for students domiciled in the eight North-Eastern states pursuing regular degree/professional courses.',
    tags: ['North East', 'UG', 'UGC', 'NER'],
  },
  {
    provider: 'University Grants Commission (UGC)',
    title: 'Maulana Azad National Fellowship for Minority Students',
    type: 'Minority',
    amount: 300000,
    amountDescription:
      '₹25,000 per month (JRF) rising to ₹28,000 (SRF), plus HRA and contingency grant, for full-time M.Phil/PhD research.',
    degree: ['Doctorate'],
    currentYearAllowed: ['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year'],
    incomeLimit: 600000,
    marksMin: 0,
    category: ['Minority'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(120),
    requiredDocuments: ['Category Certificate', 'Income Certificate', 'Bonafide / Enrolment Certificate', 'Bank Passbook', 'Photograph'],
    selectionProcess: ['Apply through the university on the UGC portal', 'Merit-based selection', 'Fellowship sanction', 'Disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { notes: 'Annual renewal based on research progress reports.' },
    officialSourceUrl: 'https://www.ugc.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.ugc.gov.in/',
    applicationSteps: [
      'Register for a full-time M.Phil/PhD as a minority community student',
      'Apply on the UGC portal',
      'Upload minority community and income certificates',
      'Track sanction and renewals',
    ],
    description:
      'National fellowship for students from notified minority communities pursuing M.Phil and PhD (family income under ₹6 lakh).',
    tags: ['minority', 'fellowship', 'research', 'UGC'],
  },
  {
    provider: 'JN Tata Endowment',
    title: 'JN Tata Endowment for Higher Education',
    type: 'Foundation',
    amount: 1000000,
    amountDescription:
      'Loan scholarship of up to ₹10,00,000 for the first year of postgraduate studies in India or abroad.',
    degree: ['Postgraduate', 'Doctorate'],
    currentYearAllowed: ['1st Year'],
    marksMin: 60,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(140),
    requiredDocuments: ['Class 12 Marksheet', 'Bonafide / Enrolment Certificate', 'Bank Passbook', 'Photograph', 'Signature'],
    selectionProcess: ['Online application', 'Shortlisting on merit', 'Interview with the Selection Committee', 'Loan scholarship award'],
    aptitudeTestRequired: false,
    renewalCriteria: { notes: 'First-year grant; continuation via separate doctoral awards where applicable.' },
    officialSourceUrl: 'https://jntataendowment.org/',
    applicationMode: 'external',
    externalPortalUrl: 'https://jntataendowment.org/',
    applicationSteps: [
      'Secure admission to a postgraduate programme',
      'Apply online in the annual call (January–March)',
      'Attend the selection interview if shortlisted',
      'Accept the loan scholarship',
    ],
    description:
      'Legacy loan scholarship for meritorious Indian graduates pursuing postgraduate studies, financing the first year of the course.',
    tags: ['foundation', 'postgraduate', 'loan-scholarship', 'Tata'],
  },
  {
    provider: 'National Scholarship Portal (NSP)',
    title: 'Post Matric Scholarship for OBC/EBC/DNT Students (PM-YASASVI)',
    type: 'Government',
    amount: 20000,
    amountDescription:
      'Maintenance allowance and fee reimbursement of ₹5,000–₹20,000 per year depending on the course group.',
    degree: ['Undergraduate', 'Postgraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['Any'],
    incomeLimit: 250000,
    marksMin: 0,
    category: ['OBC', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(40),
    requiredDocuments: [
      'Income Certificate',
      'Category Certificate',
      'Class 10 Marksheet',
      'Class 12 Marksheet',
      'Bank Passbook',
      'Photograph',
    ],
    selectionProcess: ['Online application on NSP', 'Institute verification', 'State nodal officer approval', 'DBT disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumAttendance: 75, notes: 'Annual renewal with a fresh income certificate.' },
    officialSourceUrl: 'https://scholarships.gov.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://scholarships.gov.in/',
    applicationSteps: [
      'Register on NSP under PM-YASASVI',
      'Select the OBC/EBC/DNT post-matric scheme',
      'Upload category and income certificates',
      'Submit and track state verification',
    ],
    description:
      'PM-YASASVI post-matric scholarship for OBC, EBC (economically backward) and Denotified/Nomadic Tribe students pursuing degree courses.',
    tags: ['OBC', 'post-matric', 'PM-YASASVI', 'central'],
  },
  {
    provider: 'Ministry of Tribal Affairs',
    title: 'National Fellowship for Higher Education of ST Students (NFST)',
    type: 'Government',
    amount: 300000,
    amountDescription:
      '₹25,000 per month (JRF) rising to ₹28,000 (SRF) plus HRA and contingency grant, for up to 5 years of full-time M.Phil/PhD.',
    degree: ['Doctorate'],
    currentYearAllowed: ['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year'],
    marksMin: 0,
    category: ['ST'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(120),
    requiredDocuments: ['Category Certificate', 'Bonafide / Enrolment Certificate', 'Bank Passbook', 'Photograph'],
    selectionProcess: ['Apply through the institute on the Ministry of Tribal Affairs portal', 'Merit-based selection', 'Fellowship sanction', 'Disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { notes: 'Annual renewal based on research progress reports.' },
    officialSourceUrl: 'https://tribal.nic.in/',
    applicationMode: 'external',
    externalPortalUrl: 'https://tribal.nic.in/',
    applicationSteps: [
      'Register for a full-time M.Phil/PhD as an ST student',
      'Apply on the Ministry of Tribal Affairs portal',
      'Upload tribal community and admission proof',
      'Track sanction and renewals',
    ],
    description:
      'Fellowship for Scheduled Tribe students pursuing full-time M.Phil and PhD research in universities and institutes.',
    tags: ['ST', 'fellowship', 'PhD', 'tribal'],
  },
  {
    provider: 'Sitaram Jindal Foundation',
    title: 'Sitaram Jindal Foundation Scholarship for Meritorious Students',
    type: 'Foundation',
    amount: 30000,
    amountDescription:
      'Monthly scholarship of ₹2,300–₹2,500 per month for meritorious UG/PG students in engineering, medicine and other courses.',
    degree: ['Undergraduate', 'Postgraduate', 'Professional (MBBS/BTech/LLB)'],
    currentYearAllowed: ['1st Year', '2nd Year', '3rd Year', '4th Year'],
    incomeLimit: 400000,
    marksMin: 60,
    category: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority', 'Other'],
    stateDomicile: ['All India'],
    gender: [],
    deadline: deadlineInDays(30),
    requiredDocuments: ['Income Certificate', 'Class 12 Marksheet', 'Bonafide / Enrolment Certificate', 'Bank Passbook', 'Photograph'],
    selectionProcess: ['Online application in the annual window', 'Income and merit verification', 'Selection across supported institutions', 'Monthly disbursal'],
    aptitudeTestRequired: false,
    renewalCriteria: { minimumCgpa: 6, notes: 'Renewed annually while studying at a foundation-supported institution.' },
    officialSourceUrl: 'https://www.sitaramjindalfoundation.org/scholarships-for-students-in-bangalore.php',
    applicationMode: 'external',
    externalPortalUrl: 'https://www.sitaramjindalfoundation.org/',
    applicationSteps: [
      'Check the annual application window',
      'Register on the foundation portal',
      'Upload income and academic certificates',
      'Track selection and disbursal',
    ],
    description:
      'Merit-cum-means foundation scholarship for UG and PG students (up to age 30) studying at institutions supported by the foundation.',
    tags: ['foundation', 'merit', 'UG', 'PG'],
  },
];
